package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"fmt"

	"github.com/developertom01/library-server/app/graphql/model"
	"github.com/developertom01/library-server/generated"
)

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input *model.CreateFolderInput) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// CreateFile is the resolver for the createFile field.
func (r *mutationResolver) CreateFile(ctx context.Context, input *model.CreateFileInput) (*model.File, error) {
	panic(fmt.Errorf("not implemented: CreateFile - createFile"))
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context) (*model.PaginatedFolderItems, error) {
	panic(fmt.Errorf("not implemented: Folders - folders"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
