package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"fmt"

	"github.com/developertom01/library-server/app/graphql/model"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, input *model.UploadFileInput) (string, error) {
	panic(fmt.Errorf("not implemented: UploadFile - uploadFile"))
}
