// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CurrentUserResponse interface {
	IsCurrentUserResponse()
}

type Error interface {
	IsError()
	GetMessage() string
}

type LoginResponse interface {
	IsLoginResponse()
}

type LoginFailedErrorResponse struct {
	Message string `json:"message"`
}

func (LoginFailedErrorResponse) IsError()                {}
func (this LoginFailedErrorResponse) GetMessage() string { return this.Message }

func (LoginFailedErrorResponse) IsLoginResponse() {}

type LoginInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginSuccessResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

func (LoginSuccessResponse) IsLoginResponse() {}

type SignUpInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
}

type UnAuthorizedError struct {
	Message string `json:"message"`
}

func (UnAuthorizedError) IsError()                {}
func (this UnAuthorizedError) GetMessage() string { return this.Message }

func (UnAuthorizedError) IsCurrentUserResponse() {}

type User struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     string  `json:"email"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

func (User) IsCurrentUserResponse() {}
